name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: Install make
      run: sudo apt-get install -y make

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: make test

  build-and-push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Install make
          run: sudo apt-get install -y make

        - name: Build docker image
          run: make build
